# Generated by Django 4.2.6 on 2024-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
